server:
  port: 8071
spring:
  shardingsphere:
    datasource:
      names: master,slave,slave2
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/master
        username: root
        password: root
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/slave
        username: root
        password: root
      slave2:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/slave2
        username: root
        password: root
    masterslave:
      load-balance-algorithm-type: round_robin
      master-data-source-name: master
      slave-data-source-names: slave,slave2
      name: ms
      props:
        sql:
          show: true
